/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Start a social sign-in
     * @description Builds the identity provider's authorization URL for the named social provider with a signed state carrying the validated return path, and redirects the browser to it. The browser lands on the provider's own consent screen with no intermediate page. A browser navigation, not an API call.
     */
    get: operations['startLogin']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/sign-in': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Sign in with email and password
     * @description Exchanges the credentials with the identity provider server-side. On success seals the session cookie and returns an access token. When the email is not yet verified, answers 202 with a pending token and the provider emails a six-digit code. A wrong password and an unknown email answer the same 401.
     */
    post: operations['signIn']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/sign-up': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create an account with email and password
     * @description Creates the user at the identity provider and starts email verification. Answers 202 with a pending token when the input is valid, whether or not the address already has an account, so nothing reveals which addresses are registered. An address that already has an account receives an email saying so instead of a code. When the provider does not require verification, answers 200 with a session instead.
     */
    post: operations['signUp']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/verify-email': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Complete sign-in or sign-up with the emailed code
     * @description Exchanges the pending token and the six-digit code with the identity provider. On success seals the session cookie and returns an access token. A wrong, expired, or unknown code answers 400.
     */
    post: operations['verifyEmail']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/resend-verification': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Email a new verification code
     * @description Asks the identity provider to send a fresh code to the address. The previous code stops working. Always answers 202 for a well-formed address.
     */
    post: operations['resendVerification']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/forgot-password': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Email a password reset link
     * @description Issues a single-use, expiring reset token at the identity provider and emails a link to the web app's reset page. Always answers 202 for a well-formed address.
     */
    post: operations['forgotPassword']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/reset-password': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Set a new password from a reset link
     * @description Confirms the reset token with the identity provider, sets the new password, signs the user in, seals the session cookie, and returns an access token. An expired or used token answers 400.
     */
    post: operations['resetPassword']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/callback': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Complete hosted sign-in
     * @description Return leg of the hosted flow. Verifies the state, exchanges the authorization code with the identity provider server-side, provisions the user record, seals the refresh token into the session cookie, and redirects to the web app. Every failure redirects to the web app's sign-in page with an error code and no session.
     */
    get: operations['completeLogin']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/refresh': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Exchange the session cookie for an access token
     * @description Opens the session cookie, obtains a fresh access token from the identity provider, rotates the refresh token, re-seals the cookie, and returns the access token. Requires a same-site Origin. A rejected or missing cookie clears it and answers 401.
     */
    post: operations['refreshSession']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * End the session
     * @description Revokes the identity provider session named in the cookie and clears the cookie. Requires a same-site Origin. Answers 204 even when there was no cookie, so sign-out is idempotent.
     */
    post: operations['endSession']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get the authenticated user
     * @description Returns the platform user record for the caller identified by the bearer access token. If the record is missing, the server fetches it from the identity provider and provisions it before responding.
     */
    get: operations['getMe']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/template-deliveries/download': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Generate and download an acknowledged Word template
     * @description Generates one genuine OOXML Word document from the validated contract configuration. configuration may be omitted only for the public blank template. The acknowledgment is request-scoped and must be explicitly true.
     */
    post: operations['downloadTemplateDocument']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/template-deliveries/email': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Generate and email an acknowledged Word template
     * @description Generates the same OOXML document used by direct download and attaches those bytes to an email. Success means that the configured provider has accepted the message; an unconfigured development logger never counts as delivery. configuration may be omitted only for the public blank template.
     */
    post: operations['emailTemplateDocument']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/public/sow-configurator/download': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Generate a public configured Word agreement
     * @description Validates the four public configurator answers and optional client information, then returns a genuine OOXML Word document. This operation is unauthenticated and separate from the authenticated agreement configurator. The request-scoped acknowledgment must be explicitly true.
     */
    post: operations['downloadPublicSOWDocument']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/public/sow-configurator/email': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Email a public configured Word agreement
     * @description Generates the same configured OOXML document as the public download and attaches it to an email. The frontend exposes this operation only after a real provider-backed end-to-end send has been verified.
     */
    post: operations['emailPublicSOWDocument']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/webhooks/workos': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Receive a WorkOS event
     * @description Inbound endpoint for WorkOS webhooks (user.created, user.updated, user.deleted). Authenticated by the WorkOS-Signature header, never by bearer tokens or cookies. Processing is idempotent and order-safe. Unrecognized event types are acknowledged and ignored. See specs/001-auth-landing-dashboard/contracts/workos-webhook.md.
     */
    post: operations['receiveWorkOSWebhook']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    AccessToken: {
      /** @description Short-lived bearer token for /v1 calls. Hold in memory only. */
      access_token: string
      /**
       * Format: int64
       * @description Token expiry, Unix milliseconds.
       */
      expires_at: number
    }
    User: {
      /**
       * @description Identity-provider user id (opaque text).
       * @example user_01K2Z9QH8T5XW4V3J6M0R7ANBQ
       */
      id: string
      /**
       * Format: email
       * @description The address the identity provider holds for the user.
       */
      email: string
      /** @description Display name. May be empty when the provider has none. */
      name: string
      /**
       * Format: int64
       * @description Creation time, Unix milliseconds.
       */
      created_at: number
      /**
       * Format: int64
       * @description Last provider update time, Unix milliseconds.
       */
      updated_at: number
    }
    Credentials: {
      /** Format: email */
      email: string
      password: string
    }
    SignUpRequest: {
      first_name: string
      last_name: string
      /** Format: email */
      email: string
      password: string
    }
    PendingVerification: {
      /** @description Opaque, single-use, short-lived. Send back with the code. */
      pending_token: string
    }
    VerifyEmailRequest: {
      pending_token: string
      code: string
    }
    EmailRequest: {
      /** Format: email */
      email: string
    }
    ResetPasswordRequest: {
      token: string
      password: string
    }
    DocumentDownloadRequest: {
      /**
       * @description Explicit, request-scoped legal acknowledgment.
       * @enum {boolean}
       */
      acknowledged: true
      configuration?: components['schemas']['ContractConfiguration']
    }
    EmailDocumentRequest: {
      /**
       * @description Explicit, request-scoped legal acknowledgment.
       * @enum {boolean}
       */
      acknowledged: true
      /** Format: email */
      email: string
      configuration?: components['schemas']['ContractConfiguration']
    }
    EmailDeliveryAccepted: {
      /** @enum {boolean} */
      accepted: true
    }
    PublicSOWDownloadRequest: {
      /**
       * @description Explicit, request-scoped legal acknowledgment.
       * @enum {boolean}
       */
      acknowledged: true
      client_information: components['schemas']['PublicSOWClientInformation']
      answers: components['schemas']['PublicSOWAnswers']
    }
    PublicSOWEmailRequest: {
      /**
       * @description Explicit, request-scoped legal acknowledgment.
       * @enum {boolean}
       */
      acknowledged: true
      /** Format: email */
      email: string
      client_information: components['schemas']['PublicSOWClientInformation']
      answers: components['schemas']['PublicSOWAnswers']
    }
    PublicSOWClientInformation: {
      /** @enum {string} */
      delivery_preference?: 'download' | 'email'
      /** @enum {string} */
      party_type: 'supplier' | 'buyer' | 'other'
      company_name: string
    }
    PublicSOWAnswers: {
      /** @enum {string} */
      subcontracting:
        'never_allowed' | 'buyer_written_consent' | 'notice_with_buyer_objection'
      /** @enum {string} */
      jurisdiction_rules:
        'agreement_country_terms' | 'sow_country_appendix' | 'separate_country_rider'
      /** @enum {string} */
      data_ip_liability_cap:
        'greater_of_amount_or_fee_multiple' | 'fee_multiple_only' | 'no_special_cap'
      data_ip_liability_floor_amount?: components['schemas']['ContractMoney']
      data_ip_liability_multiplier?: components['schemas']['ContractNumber']
      /** @enum {string} */
      exclusivity: 'fully_exclusive_global' | 'exclusive_limited_field' | 'non_exclusive'
      exclusivity_field_scope?: string
    }
    ContractConfiguration: {
      /** @enum {string} */
      template_version: 'content-development-1'
      organization: components['schemas']['ContractOrganization']
      steps: components['schemas']['ContractSteps']
    }
    ContractOrganization: {
      legal_name: components['schemas']['RequiredContractText']
      entity_type: components['schemas']['RequiredContractText']
      incorporation_place: components['schemas']['RequiredContractText']
      governing_law: components['schemas']['RequiredContractText']
      address: components['schemas']['RequiredContractText']
      short_name: components['schemas']['RequiredContractText']
      signer_name: components['schemas']['RequiredContractText']
      signer_title: components['schemas']['RequiredContractText']
      /** Format: email */
      signer_email: string
      contact_phone: components['schemas']['OptionalContractText']
    }
    ContractSteps: {
      agreement: components['schemas']['AgreementTerms']
      scope: components['schemas']['ContractScope']
      pricing: components['schemas']['ContractPricing']
      environment: components['schemas']['ContractEnvironment']
      technical: components['schemas']['ContractTechnical']
      delivery: components['schemas']['ContractDelivery']
      counterparty: components['schemas']['ContractCounterparty']
    }
    AgreementTerms: {
      sow_number: number
      title: components['schemas']['RequiredContractText']
      /** Format: date */
      effective_date: string
      exclusive: boolean
      materials_summary: components['schemas']['RequiredContractText']
      incident_notice_hours: components['schemas']['WholeContractNumber']
      cure_days: components['schemas']['WholeContractNumber']
      convenience_notice_days: components['schemas']['WholeContractNumber']
      records_retention_years: components['schemas']['WholeContractNumber']
      liability_lookback_months: components['schemas']['WholeContractNumber']
      excluded_claims_cap_multiplier: components['schemas']['ContractNumber']
      data_claims_cap_floor: components['schemas']['ContractMoney']
    }
    ContractScope: {
      deliverable_description: components['schemas']['RequiredContractText']
      regions: string[]
      venue_constraint: components['schemas']['RequiredContractText']
      target_volume: number
      unit: components['schemas']['RequiredContractText']
      deliverables: components['schemas']['ContractTextRows']
      /**
       * @description Whether ambient audio is permitted for this SOW.
       * @default false
       */
      ambient_audio: boolean
      notes: components['schemas']['OptionalContractText']
    }
    ContractPricing: {
      currency: string
      unit_fee: components['schemas']['ContractMoney']
      deposit_required: boolean
      deposit_amount: components['schemas']['ContractMoney'] | null
      invoicing_cadence: components['schemas']['RequiredContractText']
      payment_terms_days: components['schemas']['WholeContractNumber']
      payment_methods: components['schemas']['RequiredContractText']
      /** Format: email */
      invoice_email: string
      milestones: components['schemas']['ContractMilestone'][]
      firm_deadline: boolean
    }
    ContractMilestone: {
      name: components['schemas']['RequiredContractText']
      volume: components['schemas']['RequiredContractText']
      /** Format: date */
      deadline: string
      notes: components['schemas']['OptionalContractText']
      is_final: boolean
    }
    ContractEnvironment: {
      verticals: components['schemas']['ContractVertical'][]
      limits: components['schemas']['ContractLimit'][]
      difficulty: components['schemas']['ContractDifficulty']
      difficulty_caps: components['schemas']['ContractDifficultyCap'][]
      plan_required: boolean
      change_window_hours: components['schemas']['WholeContractNumber']
      extra_prohibited: components['schemas']['OptionalContractTextRows']
      extra_excluded_settings: components['schemas']['OptionalContractTextRows']
    }
    ContractVertical: {
      verticals: components['schemas']['RequiredContractText']
      target: components['schemas']['RequiredContractText']
      details: components['schemas']['RequiredContractText']
    }
    ContractLimit: {
      limit: components['schemas']['RequiredContractText']
      value: string
      unit: components['schemas']['OptionalContractText']
    }
    ContractDifficulty: {
      easy: components['schemas']['Percent']
      medium: components['schemas']['Percent']
      hard: components['schemas']['Percent']
    }
    ContractDifficultyCap: {
      scope: components['schemas']['RequiredContractText']
      easy: components['schemas']['DecimalText']
      medium: components['schemas']['DecimalText']
      hard: components['schemas']['DecimalText']
    }
    ContractTechnical: {
      requirements: components['schemas']['ContractRequirement'][]
      pre_collection_materials: components['schemas']['OptionalContractTextRows']
      condition_of_payment: boolean
    }
    ContractRequirement: {
      requirement: components['schemas']['RequiredContractText']
      specification: components['schemas']['RequiredContractText']
      rejection: components['schemas']['RequiredContractText']
    }
    ContractDelivery: {
      storage_location: components['schemas']['RequiredContractText']
      delivery_cadence: components['schemas']['RequiredContractText']
      manifest_format: components['schemas']['RequiredContractText']
      manifest_fields: components['schemas']['ContractTextRows']
      site_data_fields: components['schemas']['OptionalContractTextRows']
      integrity_text: components['schemas']['RequiredContractText']
      review_window_days: components['schemas']['WholeContractNumber']
      correction_days: components['schemas']['WholeContractNumber']
      deemed_acceptance: boolean
      rejected_stays_developer_owned: boolean
      deletion_window_days: components['schemas']['WholeContractNumber']
    }
    ContractCounterparty: {
      /** @enum {string} */
      mode: 'details' | 'invite'
      /** Format: email */
      email: string
      legal_name: components['schemas']['OptionalContractText']
      entity_jurisdiction: components['schemas']['OptionalContractText']
      address: components['schemas']['OptionalContractText']
      short_name: components['schemas']['OptionalContractText']
      signatory_name: components['schemas']['OptionalContractText']
      signatory_title: components['schemas']['OptionalContractText']
      cc_emails: components['schemas']['OptionalContractText']
    }
    ContractTextRow: {
      text: components['schemas']['RequiredContractText']
    }
    ContractTextRows: components['schemas']['ContractTextRow'][]
    OptionalContractTextRows: components['schemas']['ContractTextRow'][]
    RequiredContractText: string
    OptionalContractText: string
    DecimalText: string
    ContractNumber: number
    WholeContractNumber: number
    ContractMoney: number
    Percent: number
    /** @description WorkOS event envelope. data carries the provider's user object for user.* events; its shape is owned by WorkOS and validated structurally, not exhaustively. */
    WorkOSEvent: {
      /** @description Event id, used for idempotent processing. */
      id: string
      /** @description Event type, e.g. user.created. */
      event: string
      data: {
        [key: string]: unknown
      }
      /** @description ISO 8601 event creation time (provider-owned format). */
      created_at: string
    }
    Error: {
      /** @description Machine-readable snake_case error code. */
      error: string
      /** @description Correlation id to quote in a support request. */
      request_id?: string
      /** @description Optional structured detail (validation errors and similar). */
      details?: unknown
    }
  }
  responses: {
    /** @description Missing, malformed, expired, or otherwise invalid credential. */
    Unauthorized: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description The Origin header is missing or not an allowed web origin. */
    ForbiddenOrigin: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description Rate limit exceeded. */
    TooManyRequests: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description The identity provider could not be reached. */
    ProviderUnavailable: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description Signed in. The session cookie is set alongside. */
    SessionStarted: {
      headers: {
        'Set-Cookie'?: string
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['AccessToken']
      }
    }
    /** @description The email must be verified before a session starts. */
    VerificationPending: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['PendingVerification']
      }
    }
    /** @description Malformed input. details lists field errors. */
    ValidationFailed: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description The email and password do not match an account. */
    InvalidCredentials: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description The identity provider rejected the password. details.message says why. */
    WeakPassword: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description The Word document could not be generated. */
    GenerationFailed: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description Email delivery is unconfigured or the provider rejected the message. */
    EmailDeliveryUnavailable: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
  }
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  startLogin: {
    parameters: {
      query: {
        provider: 'google'
        /** @description Same-app absolute path to land on after sign-in. Invalid values fall back to /dashboard. */
        returnTo?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Redirect to the social provider. */
      302: {
        headers: {
          Location?: string
          [name: string]: unknown
        }
        content?: never
      }
      400: components['responses']['ValidationFailed']
      429: components['responses']['TooManyRequests']
    }
  }
  signIn: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['Credentials']
      }
    }
    responses: {
      200: components['responses']['SessionStarted']
      202: components['responses']['VerificationPending']
      400: components['responses']['ValidationFailed']
      401: components['responses']['InvalidCredentials']
      403: components['responses']['ForbiddenOrigin']
      429: components['responses']['TooManyRequests']
      503: components['responses']['ProviderUnavailable']
    }
  }
  signUp: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SignUpRequest']
      }
    }
    responses: {
      200: components['responses']['SessionStarted']
      202: components['responses']['VerificationPending']
      400: components['responses']['ValidationFailed']
      403: components['responses']['ForbiddenOrigin']
      422: components['responses']['WeakPassword']
      429: components['responses']['TooManyRequests']
      503: components['responses']['ProviderUnavailable']
    }
  }
  verifyEmail: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['VerifyEmailRequest']
      }
    }
    responses: {
      200: components['responses']['SessionStarted']
      /** @description Malformed input (validation_failed) or a rejected code (invalid_code). */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      403: components['responses']['ForbiddenOrigin']
      429: components['responses']['TooManyRequests']
      503: components['responses']['ProviderUnavailable']
    }
  }
  resendVerification: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EmailRequest']
      }
    }
    responses: {
      /** @description Accepted. */
      202: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      400: components['responses']['ValidationFailed']
      403: components['responses']['ForbiddenOrigin']
      429: components['responses']['TooManyRequests']
    }
  }
  forgotPassword: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EmailRequest']
      }
    }
    responses: {
      /** @description Accepted. */
      202: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      400: components['responses']['ValidationFailed']
      403: components['responses']['ForbiddenOrigin']
      429: components['responses']['TooManyRequests']
    }
  }
  resetPassword: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ResetPasswordRequest']
      }
    }
    responses: {
      200: components['responses']['SessionStarted']
      /** @description Malformed input (validation_failed) or a rejected token (invalid_reset_token). */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      403: components['responses']['ForbiddenOrigin']
      422: components['responses']['WeakPassword']
      429: components['responses']['TooManyRequests']
      503: components['responses']['ProviderUnavailable']
    }
  }
  completeLogin: {
    parameters: {
      query?: {
        code?: string
        state?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Redirect to WEB_APP_URL/callback?returnTo=… on success, or to WEB_APP_URL/?error=… on failure. */
      302: {
        headers: {
          Location?: string
          /** @description The sealed session cookie, or a clearing cookie on failure. */
          'Set-Cookie'?: string
          [name: string]: unknown
        }
        content?: never
      }
      429: components['responses']['TooManyRequests']
    }
  }
  refreshSession: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description A fresh access token. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AccessToken']
        }
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['ForbiddenOrigin']
      429: components['responses']['TooManyRequests']
      503: components['responses']['ProviderUnavailable']
    }
  }
  endSession: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Session ended and cookie cleared. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      403: components['responses']['ForbiddenOrigin']
      429: components['responses']['TooManyRequests']
    }
  }
  getMe: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The authenticated user's record. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
      401: components['responses']['Unauthorized']
    }
  }
  downloadTemplateDocument: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['DocumentDownloadRequest']
      }
    }
    responses: {
      /** @description The generated Microsoft Word document. */
      200: {
        headers: {
          'Content-Disposition': string
          'Cache-Control': string
          [name: string]: unknown
        }
        content: {
          'application/vnd.openxmlformats-officedocument.wordprocessingml.document': string
        }
      }
      400: components['responses']['ValidationFailed']
      403: components['responses']['ForbiddenOrigin']
      429: components['responses']['TooManyRequests']
      500: components['responses']['GenerationFailed']
    }
  }
  emailTemplateDocument: {
    parameters: {
      query?: never
      header: {
        /** @description Opaque request key used to prevent an accidental duplicate send. Do not include an email address or contract value in this key. */
        'Idempotency-Key': string
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EmailDocumentRequest']
      }
    }
    responses: {
      /** @description The email provider accepted the message and attachment. */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EmailDeliveryAccepted']
        }
      }
      400: components['responses']['ValidationFailed']
      403: components['responses']['ForbiddenOrigin']
      /** @description The idempotency key was already used for different input. */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      429: components['responses']['TooManyRequests']
      500: components['responses']['GenerationFailed']
      503: components['responses']['EmailDeliveryUnavailable']
    }
  }
  downloadPublicSOWDocument: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PublicSOWDownloadRequest']
      }
    }
    responses: {
      /** @description The configured Microsoft Word agreement. */
      200: {
        headers: {
          'Content-Disposition': string
          'Cache-Control': string
          [name: string]: unknown
        }
        content: {
          'application/vnd.openxmlformats-officedocument.wordprocessingml.document': string
        }
      }
      400: components['responses']['ValidationFailed']
      403: components['responses']['ForbiddenOrigin']
      429: components['responses']['TooManyRequests']
      500: components['responses']['GenerationFailed']
    }
  }
  emailPublicSOWDocument: {
    parameters: {
      query?: never
      header: {
        /** @description Opaque key for suppressing an accidental duplicate send. */
        'Idempotency-Key': string
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PublicSOWEmailRequest']
      }
    }
    responses: {
      /** @description The configured provider accepted the email and attachment. */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EmailDeliveryAccepted']
        }
      }
      400: components['responses']['ValidationFailed']
      403: components['responses']['ForbiddenOrigin']
      /** @description The idempotency key was already used for different input. */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      429: components['responses']['TooManyRequests']
      500: components['responses']['GenerationFailed']
      503: components['responses']['EmailDeliveryUnavailable']
    }
  }
  receiveWorkOSWebhook: {
    parameters: {
      query?: never
      header: {
        /** @description t=<unix-ms>, v1=<hex HMAC-SHA256 of "t.body"> */
        'WorkOS-Signature': string
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['WorkOSEvent']
      }
    }
    responses: {
      /** @description Event verified and processed (or acknowledged as ignored). */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Body is not a parseable WorkOS event. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      401: components['responses']['Unauthorized']
    }
  }
}
