// Package dto provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package dto

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ContractConfigurationTemplateVersion.
const (
	ContractConfigurationTemplateVersionContentDevelopment1 ContractConfigurationTemplateVersion = "content-development-1"
)

// Valid indicates whether the value is a known member of the ContractConfigurationTemplateVersion enum.
func (e ContractConfigurationTemplateVersion) Valid() bool {
	switch e {
	case ContractConfigurationTemplateVersionContentDevelopment1:
		return true
	default:
		return false
	}
}

// Defines values for ContractCounterpartyMode.
const (
	ContractCounterpartyModeDetails ContractCounterpartyMode = "details"
	ContractCounterpartyModeInvite  ContractCounterpartyMode = "invite"
)

// Valid indicates whether the value is a known member of the ContractCounterpartyMode enum.
func (e ContractCounterpartyMode) Valid() bool {
	switch e {
	case ContractCounterpartyModeDetails:
		return true
	case ContractCounterpartyModeInvite:
		return true
	default:
		return false
	}
}

// Defines values for DocumentDownloadRequestAcknowledged.
const (
	DocumentDownloadRequestAcknowledgedTrue DocumentDownloadRequestAcknowledged = true
)

// Valid indicates whether the value is a known member of the DocumentDownloadRequestAcknowledged enum.
func (e DocumentDownloadRequestAcknowledged) Valid() bool {
	switch e {
	case DocumentDownloadRequestAcknowledgedTrue:
		return true
	default:
		return false
	}
}

// Defines values for EmailDeliveryAcceptedAccepted.
const (
	EmailDeliveryAcceptedAcceptedTrue EmailDeliveryAcceptedAccepted = true
)

// Valid indicates whether the value is a known member of the EmailDeliveryAcceptedAccepted enum.
func (e EmailDeliveryAcceptedAccepted) Valid() bool {
	switch e {
	case EmailDeliveryAcceptedAcceptedTrue:
		return true
	default:
		return false
	}
}

// Defines values for EmailDocumentRequestAcknowledged.
const (
	EmailDocumentRequestAcknowledgedTrue EmailDocumentRequestAcknowledged = true
)

// Valid indicates whether the value is a known member of the EmailDocumentRequestAcknowledged enum.
func (e EmailDocumentRequestAcknowledged) Valid() bool {
	switch e {
	case EmailDocumentRequestAcknowledgedTrue:
		return true
	default:
		return false
	}
}

// Defines values for PublicSOWAnswersDataIpLiabilityCap.
const (
	PublicSOWAnswersDataIpLiabilityCapFeeMultipleOnly              PublicSOWAnswersDataIpLiabilityCap = "fee_multiple_only"
	PublicSOWAnswersDataIpLiabilityCapGreaterOfAmountOrFeeMultiple PublicSOWAnswersDataIpLiabilityCap = "greater_of_amount_or_fee_multiple"
	PublicSOWAnswersDataIpLiabilityCapNoSpecialCap                 PublicSOWAnswersDataIpLiabilityCap = "no_special_cap"
)

// Valid indicates whether the value is a known member of the PublicSOWAnswersDataIpLiabilityCap enum.
func (e PublicSOWAnswersDataIpLiabilityCap) Valid() bool {
	switch e {
	case PublicSOWAnswersDataIpLiabilityCapFeeMultipleOnly:
		return true
	case PublicSOWAnswersDataIpLiabilityCapGreaterOfAmountOrFeeMultiple:
		return true
	case PublicSOWAnswersDataIpLiabilityCapNoSpecialCap:
		return true
	default:
		return false
	}
}

// Defines values for PublicSOWAnswersExclusivity.
const (
	PublicSOWAnswersExclusivityExclusiveLimitedField PublicSOWAnswersExclusivity = "exclusive_limited_field"
	PublicSOWAnswersExclusivityFullyExclusiveGlobal  PublicSOWAnswersExclusivity = "fully_exclusive_global"
	PublicSOWAnswersExclusivityNonExclusive          PublicSOWAnswersExclusivity = "non_exclusive"
)

// Valid indicates whether the value is a known member of the PublicSOWAnswersExclusivity enum.
func (e PublicSOWAnswersExclusivity) Valid() bool {
	switch e {
	case PublicSOWAnswersExclusivityExclusiveLimitedField:
		return true
	case PublicSOWAnswersExclusivityFullyExclusiveGlobal:
		return true
	case PublicSOWAnswersExclusivityNonExclusive:
		return true
	default:
		return false
	}
}

// Defines values for PublicSOWAnswersJurisdictionRules.
const (
	PublicSOWAnswersJurisdictionRulesAgreementCountryTerms PublicSOWAnswersJurisdictionRules = "agreement_country_terms"
	PublicSOWAnswersJurisdictionRulesSeparateCountryRider  PublicSOWAnswersJurisdictionRules = "separate_country_rider"
	PublicSOWAnswersJurisdictionRulesSowCountryAppendix    PublicSOWAnswersJurisdictionRules = "sow_country_appendix"
)

// Valid indicates whether the value is a known member of the PublicSOWAnswersJurisdictionRules enum.
func (e PublicSOWAnswersJurisdictionRules) Valid() bool {
	switch e {
	case PublicSOWAnswersJurisdictionRulesAgreementCountryTerms:
		return true
	case PublicSOWAnswersJurisdictionRulesSeparateCountryRider:
		return true
	case PublicSOWAnswersJurisdictionRulesSowCountryAppendix:
		return true
	default:
		return false
	}
}

// Defines values for PublicSOWAnswersSubcontracting.
const (
	PublicSOWAnswersSubcontractingBuyerWrittenConsent      PublicSOWAnswersSubcontracting = "buyer_written_consent"
	PublicSOWAnswersSubcontractingNeverAllowed             PublicSOWAnswersSubcontracting = "never_allowed"
	PublicSOWAnswersSubcontractingNoticeWithBuyerObjection PublicSOWAnswersSubcontracting = "notice_with_buyer_objection"
)

// Valid indicates whether the value is a known member of the PublicSOWAnswersSubcontracting enum.
func (e PublicSOWAnswersSubcontracting) Valid() bool {
	switch e {
	case PublicSOWAnswersSubcontractingBuyerWrittenConsent:
		return true
	case PublicSOWAnswersSubcontractingNeverAllowed:
		return true
	case PublicSOWAnswersSubcontractingNoticeWithBuyerObjection:
		return true
	default:
		return false
	}
}

// Defines values for PublicSOWClientInformationDeliveryPreference.
const (
	PublicSOWClientInformationDeliveryPreferenceDownload PublicSOWClientInformationDeliveryPreference = "download"
	PublicSOWClientInformationDeliveryPreferenceEmail    PublicSOWClientInformationDeliveryPreference = "email"
)

// Valid indicates whether the value is a known member of the PublicSOWClientInformationDeliveryPreference enum.
func (e PublicSOWClientInformationDeliveryPreference) Valid() bool {
	switch e {
	case PublicSOWClientInformationDeliveryPreferenceDownload:
		return true
	case PublicSOWClientInformationDeliveryPreferenceEmail:
		return true
	default:
		return false
	}
}

// Defines values for PublicSOWClientInformationPartyType.
const (
	PublicSOWClientInformationPartyTypeBuyer    PublicSOWClientInformationPartyType = "buyer"
	PublicSOWClientInformationPartyTypeOther    PublicSOWClientInformationPartyType = "other"
	PublicSOWClientInformationPartyTypeSupplier PublicSOWClientInformationPartyType = "supplier"
)

// Valid indicates whether the value is a known member of the PublicSOWClientInformationPartyType enum.
func (e PublicSOWClientInformationPartyType) Valid() bool {
	switch e {
	case PublicSOWClientInformationPartyTypeBuyer:
		return true
	case PublicSOWClientInformationPartyTypeOther:
		return true
	case PublicSOWClientInformationPartyTypeSupplier:
		return true
	default:
		return false
	}
}

// Defines values for PublicSOWDownloadRequestAcknowledged.
const (
	PublicSOWDownloadRequestAcknowledgedTrue PublicSOWDownloadRequestAcknowledged = true
)

// Valid indicates whether the value is a known member of the PublicSOWDownloadRequestAcknowledged enum.
func (e PublicSOWDownloadRequestAcknowledged) Valid() bool {
	switch e {
	case PublicSOWDownloadRequestAcknowledgedTrue:
		return true
	default:
		return false
	}
}

// Defines values for PublicSOWEmailRequestAcknowledged.
const (
	PublicSOWEmailRequestAcknowledgedTrue PublicSOWEmailRequestAcknowledged = true
)

// Valid indicates whether the value is a known member of the PublicSOWEmailRequestAcknowledged enum.
func (e PublicSOWEmailRequestAcknowledged) Valid() bool {
	switch e {
	case PublicSOWEmailRequestAcknowledgedTrue:
		return true
	default:
		return false
	}
}

// Defines values for StartLoginParamsProvider.
const (
	StartLoginParamsProviderGoogle StartLoginParamsProvider = "google"
)

// Valid indicates whether the value is a known member of the StartLoginParamsProvider enum.
func (e StartLoginParamsProvider) Valid() bool {
	switch e {
	case StartLoginParamsProviderGoogle:
		return true
	default:
		return false
	}
}

// AccessToken defines model for AccessToken.
type AccessToken struct {
	// AccessToken Short-lived bearer token for /v1 calls. Hold in memory only.
	AccessToken string `json:"access_token"`

	// ExpiresAt Token expiry, Unix milliseconds.
	ExpiresAt int64 `json:"expires_at"`
}

// AgreementTerms defines model for AgreementTerms.
type AgreementTerms struct {
	ConvenienceNoticeDays       WholeContractNumber  `json:"convenience_notice_days"`
	CureDays                    WholeContractNumber  `json:"cure_days"`
	DataClaimsCapFloor          ContractMoney        `json:"data_claims_cap_floor"`
	EffectiveDate               openapi_types.Date   `json:"effective_date"`
	ExcludedClaimsCapMultiplier ContractNumber       `json:"excluded_claims_cap_multiplier"`
	Exclusive                   bool                 `json:"exclusive"`
	IncidentNoticeHours         WholeContractNumber  `json:"incident_notice_hours"`
	LiabilityLookbackMonths     WholeContractNumber  `json:"liability_lookback_months"`
	MaterialsSummary            RequiredContractText `json:"materials_summary"`
	RecordsRetentionYears       WholeContractNumber  `json:"records_retention_years"`
	SowNumber                   int                  `json:"sow_number"`
	Title                       RequiredContractText `json:"title"`
}

// ContractConfiguration defines model for ContractConfiguration.
type ContractConfiguration struct {
	Organization    ContractOrganization                 `json:"organization"`
	Steps           ContractSteps                        `json:"steps"`
	TemplateVersion ContractConfigurationTemplateVersion `json:"template_version"`
}

// ContractConfigurationTemplateVersion defines model for ContractConfiguration.TemplateVersion.
type ContractConfigurationTemplateVersion string

// ContractCounterparty defines model for ContractCounterparty.
type ContractCounterparty struct {
	Address            OptionalContractText     `json:"address"`
	CcEmails           OptionalContractText     `json:"cc_emails"`
	Email              openapi_types.Email      `json:"email"`
	EntityJurisdiction OptionalContractText     `json:"entity_jurisdiction"`
	LegalName          OptionalContractText     `json:"legal_name"`
	Mode               ContractCounterpartyMode `json:"mode"`
	ShortName          OptionalContractText     `json:"short_name"`
	SignatoryName      OptionalContractText     `json:"signatory_name"`
	SignatoryTitle     OptionalContractText     `json:"signatory_title"`
}

// ContractCounterpartyMode defines model for ContractCounterparty.Mode.
type ContractCounterpartyMode string

// ContractDelivery defines model for ContractDelivery.
type ContractDelivery struct {
	CorrectionDays              WholeContractNumber      `json:"correction_days"`
	DeemedAcceptance            bool                     `json:"deemed_acceptance"`
	DeletionWindowDays          WholeContractNumber      `json:"deletion_window_days"`
	DeliveryCadence             RequiredContractText     `json:"delivery_cadence"`
	IntegrityText               RequiredContractText     `json:"integrity_text"`
	ManifestFields              ContractTextRows         `json:"manifest_fields"`
	ManifestFormat              RequiredContractText     `json:"manifest_format"`
	RejectedStaysDeveloperOwned bool                     `json:"rejected_stays_developer_owned"`
	ReviewWindowDays            WholeContractNumber      `json:"review_window_days"`
	SiteDataFields              OptionalContractTextRows `json:"site_data_fields"`
	StorageLocation             RequiredContractText     `json:"storage_location"`
}

// ContractDifficulty defines model for ContractDifficulty.
type ContractDifficulty struct {
	Easy   Percent `json:"easy"`
	Hard   Percent `json:"hard"`
	Medium Percent `json:"medium"`
}

// ContractDifficultyCap defines model for ContractDifficultyCap.
type ContractDifficultyCap struct {
	Easy   DecimalText          `json:"easy"`
	Hard   DecimalText          `json:"hard"`
	Medium DecimalText          `json:"medium"`
	Scope  RequiredContractText `json:"scope"`
}

// ContractEnvironment defines model for ContractEnvironment.
type ContractEnvironment struct {
	ChangeWindowHours     WholeContractNumber      `json:"change_window_hours"`
	Difficulty            ContractDifficulty       `json:"difficulty"`
	DifficultyCaps        []ContractDifficultyCap  `json:"difficulty_caps"`
	ExtraExcludedSettings OptionalContractTextRows `json:"extra_excluded_settings"`
	ExtraProhibited       OptionalContractTextRows `json:"extra_prohibited"`
	Limits                []ContractLimit          `json:"limits"`
	PlanRequired          bool                     `json:"plan_required"`
	Verticals             []ContractVertical       `json:"verticals"`
}

// ContractLimit defines model for ContractLimit.
type ContractLimit struct {
	Limit RequiredContractText `json:"limit"`
	Unit  OptionalContractText `json:"unit"`
	Value string               `json:"value"`
}

// ContractMilestone defines model for ContractMilestone.
type ContractMilestone struct {
	Deadline openapi_types.Date   `json:"deadline"`
	IsFinal  bool                 `json:"is_final"`
	Name     RequiredContractText `json:"name"`
	Notes    OptionalContractText `json:"notes"`
	Volume   RequiredContractText `json:"volume"`
}

// ContractMoney defines model for ContractMoney.
type ContractMoney = float32

// ContractNumber defines model for ContractNumber.
type ContractNumber = float32

// ContractOrganization defines model for ContractOrganization.
type ContractOrganization struct {
	Address            RequiredContractText `json:"address"`
	ContactPhone       OptionalContractText `json:"contact_phone"`
	EntityType         RequiredContractText `json:"entity_type"`
	GoverningLaw       RequiredContractText `json:"governing_law"`
	IncorporationPlace RequiredContractText `json:"incorporation_place"`
	LegalName          RequiredContractText `json:"legal_name"`
	ShortName          RequiredContractText `json:"short_name"`
	SignerEmail        openapi_types.Email  `json:"signer_email"`
	SignerName         RequiredContractText `json:"signer_name"`
	SignerTitle        RequiredContractText `json:"signer_title"`
}

// ContractPricing defines model for ContractPricing.
type ContractPricing struct {
	Currency         string               `json:"currency"`
	DepositAmount    *ContractMoney       `json:"deposit_amount"`
	DepositRequired  bool                 `json:"deposit_required"`
	FirmDeadline     bool                 `json:"firm_deadline"`
	InvoiceEmail     openapi_types.Email  `json:"invoice_email"`
	InvoicingCadence RequiredContractText `json:"invoicing_cadence"`
	Milestones       []ContractMilestone  `json:"milestones"`
	PaymentMethods   RequiredContractText `json:"payment_methods"`
	PaymentTermsDays WholeContractNumber  `json:"payment_terms_days"`
	UnitFee          ContractMoney        `json:"unit_fee"`
}

// ContractRequirement defines model for ContractRequirement.
type ContractRequirement struct {
	Rejection     RequiredContractText `json:"rejection"`
	Requirement   RequiredContractText `json:"requirement"`
	Specification RequiredContractText `json:"specification"`
}

// ContractScope defines model for ContractScope.
type ContractScope struct {
	// AmbientAudio Whether ambient audio is permitted for this SOW.
	AmbientAudio           *bool                `json:"ambient_audio,omitempty"`
	DeliverableDescription RequiredContractText `json:"deliverable_description"`
	Deliverables           ContractTextRows     `json:"deliverables"`
	Notes                  OptionalContractText `json:"notes"`
	Regions                []string             `json:"regions"`
	TargetVolume           float32              `json:"target_volume"`
	Unit                   RequiredContractText `json:"unit"`
	VenueConstraint        RequiredContractText `json:"venue_constraint"`
}

// ContractSteps defines model for ContractSteps.
type ContractSteps struct {
	Agreement    AgreementTerms       `json:"agreement"`
	Counterparty ContractCounterparty `json:"counterparty"`
	Delivery     ContractDelivery     `json:"delivery"`
	Environment  ContractEnvironment  `json:"environment"`
	Pricing      ContractPricing      `json:"pricing"`
	Scope        ContractScope        `json:"scope"`
	Technical    ContractTechnical    `json:"technical"`
}

// ContractTechnical defines model for ContractTechnical.
type ContractTechnical struct {
	ConditionOfPayment     bool                     `json:"condition_of_payment"`
	PreCollectionMaterials OptionalContractTextRows `json:"pre_collection_materials"`
	Requirements           []ContractRequirement    `json:"requirements"`
}

// ContractTextRow defines model for ContractTextRow.
type ContractTextRow struct {
	Text RequiredContractText `json:"text"`
}

// ContractTextRows defines model for ContractTextRows.
type ContractTextRows = []ContractTextRow

// ContractVertical defines model for ContractVertical.
type ContractVertical struct {
	Details   RequiredContractText `json:"details"`
	Target    RequiredContractText `json:"target"`
	Verticals RequiredContractText `json:"verticals"`
}

// Credentials defines model for Credentials.
type Credentials struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// DecimalText defines model for DecimalText.
type DecimalText = string

// DocumentDownloadRequest defines model for DocumentDownloadRequest.
type DocumentDownloadRequest struct {
	// Acknowledged Explicit, request-scoped legal acknowledgment.
	Acknowledged  DocumentDownloadRequestAcknowledged `json:"acknowledged"`
	Configuration *ContractConfiguration              `json:"configuration,omitempty"`
}

// DocumentDownloadRequestAcknowledged Explicit, request-scoped legal acknowledgment.
type DocumentDownloadRequestAcknowledged bool

// EmailDeliveryAccepted defines model for EmailDeliveryAccepted.
type EmailDeliveryAccepted struct {
	Accepted EmailDeliveryAcceptedAccepted `json:"accepted"`
}

// EmailDeliveryAcceptedAccepted defines model for EmailDeliveryAccepted.Accepted.
type EmailDeliveryAcceptedAccepted bool

// EmailDocumentRequest defines model for EmailDocumentRequest.
type EmailDocumentRequest struct {
	// Acknowledged Explicit, request-scoped legal acknowledgment.
	Acknowledged  EmailDocumentRequestAcknowledged `json:"acknowledged"`
	Configuration *ContractConfiguration           `json:"configuration,omitempty"`
	Email         openapi_types.Email              `json:"email"`
}

// EmailDocumentRequestAcknowledged Explicit, request-scoped legal acknowledgment.
type EmailDocumentRequestAcknowledged bool

// EmailRequest defines model for EmailRequest.
type EmailRequest struct {
	Email openapi_types.Email `json:"email"`
}

// Error defines model for Error.
type Error struct {
	// Details Optional structured detail (validation errors and similar).
	Details interface{} `json:"details,omitempty"`

	// Error Machine-readable snake_case error code.
	Error string `json:"error"`

	// RequestId Correlation id to quote in a support request.
	RequestId *string `json:"request_id,omitempty"`
}

// OptionalContractText defines model for OptionalContractText.
type OptionalContractText = string

// OptionalContractTextRows defines model for OptionalContractTextRows.
type OptionalContractTextRows = []ContractTextRow

// PendingVerification defines model for PendingVerification.
type PendingVerification struct {
	// PendingToken Opaque, single-use, short-lived. Send back with the code.
	PendingToken string `json:"pending_token"`
}

// Percent defines model for Percent.
type Percent = float32

// PublicSOWAnswers defines model for PublicSOWAnswers.
type PublicSOWAnswers struct {
	DataIpLiabilityCap         PublicSOWAnswersDataIpLiabilityCap `json:"data_ip_liability_cap"`
	DataIpLiabilityFloorAmount *ContractMoney                     `json:"data_ip_liability_floor_amount,omitempty"`
	DataIpLiabilityMultiplier  *ContractNumber                    `json:"data_ip_liability_multiplier,omitempty"`
	Exclusivity                PublicSOWAnswersExclusivity        `json:"exclusivity"`
	ExclusivityFieldScope      *string                            `json:"exclusivity_field_scope,omitempty"`
	JurisdictionRules          PublicSOWAnswersJurisdictionRules  `json:"jurisdiction_rules"`
	Subcontracting             PublicSOWAnswersSubcontracting     `json:"subcontracting"`
}

// PublicSOWAnswersDataIpLiabilityCap defines model for PublicSOWAnswers.DataIpLiabilityCap.
type PublicSOWAnswersDataIpLiabilityCap string

// PublicSOWAnswersExclusivity defines model for PublicSOWAnswers.Exclusivity.
type PublicSOWAnswersExclusivity string

// PublicSOWAnswersJurisdictionRules defines model for PublicSOWAnswers.JurisdictionRules.
type PublicSOWAnswersJurisdictionRules string

// PublicSOWAnswersSubcontracting defines model for PublicSOWAnswers.Subcontracting.
type PublicSOWAnswersSubcontracting string

// PublicSOWClientInformation defines model for PublicSOWClientInformation.
type PublicSOWClientInformation struct {
	CompanyName        string                                        `json:"company_name"`
	DeliveryPreference *PublicSOWClientInformationDeliveryPreference `json:"delivery_preference,omitempty"`
	PartyType          PublicSOWClientInformationPartyType           `json:"party_type"`
}

// PublicSOWClientInformationDeliveryPreference defines model for PublicSOWClientInformation.DeliveryPreference.
type PublicSOWClientInformationDeliveryPreference string

// PublicSOWClientInformationPartyType defines model for PublicSOWClientInformation.PartyType.
type PublicSOWClientInformationPartyType string

// PublicSOWDownloadRequest defines model for PublicSOWDownloadRequest.
type PublicSOWDownloadRequest struct {
	// Acknowledged Explicit, request-scoped legal acknowledgment.
	Acknowledged      PublicSOWDownloadRequestAcknowledged `json:"acknowledged"`
	Answers           PublicSOWAnswers                     `json:"answers"`
	ClientInformation PublicSOWClientInformation           `json:"client_information"`
}

// PublicSOWDownloadRequestAcknowledged Explicit, request-scoped legal acknowledgment.
type PublicSOWDownloadRequestAcknowledged bool

// PublicSOWEmailRequest defines model for PublicSOWEmailRequest.
type PublicSOWEmailRequest struct {
	// Acknowledged Explicit, request-scoped legal acknowledgment.
	Acknowledged      PublicSOWEmailRequestAcknowledged `json:"acknowledged"`
	Answers           PublicSOWAnswers                  `json:"answers"`
	ClientInformation PublicSOWClientInformation        `json:"client_information"`
	Email             openapi_types.Email               `json:"email"`
}

// PublicSOWEmailRequestAcknowledged Explicit, request-scoped legal acknowledgment.
type PublicSOWEmailRequestAcknowledged bool

// RequiredContractText defines model for RequiredContractText.
type RequiredContractText = string

// ResetPasswordRequest defines model for ResetPasswordRequest.
type ResetPasswordRequest struct {
	Password string `json:"password"`
	Token    string `json:"token"`
}

// SignUpRequest defines model for SignUpRequest.
type SignUpRequest struct {
	Email     openapi_types.Email `json:"email"`
	FirstName string              `json:"first_name"`
	LastName  string              `json:"last_name"`
	Password  string              `json:"password"`
}

// User defines model for User.
type User struct {
	// CreatedAt Creation time, Unix milliseconds.
	CreatedAt int64 `json:"created_at"`

	// Email The address the identity provider holds for the user.
	Email openapi_types.Email `json:"email"`

	// Id Identity-provider user id (opaque text).
	//
	// Examples: user_01K2Z9QH8T5XW4V3J6M0R7ANBQ
	Id string `json:"id"`

	// Name Display name. May be empty when the provider has none.
	Name string `json:"name"`

	// UpdatedAt Last provider update time, Unix milliseconds.
	UpdatedAt int64 `json:"updated_at"`
}

// VerifyEmailRequest defines model for VerifyEmailRequest.
type VerifyEmailRequest struct {
	Code         string `json:"code"`
	PendingToken string `json:"pending_token"`
}

// WholeContractNumber defines model for WholeContractNumber.
type WholeContractNumber = int

// WorkOSEvent WorkOS event envelope. data carries the provider's user object for user.* events; its shape is owned by WorkOS and validated structurally, not exhaustively.
type WorkOSEvent struct {
	// CreatedAt ISO 8601 event creation time (provider-owned format).
	CreatedAt string                 `json:"created_at"`
	Data      map[string]interface{} `json:"data"`

	// Event Event type, e.g. user.created.
	Event string `json:"event"`

	// Id Event id, used for idempotent processing.
	Id string `json:"id"`
}

// EmailDeliveryUnavailable defines model for EmailDeliveryUnavailable.
type EmailDeliveryUnavailable = Error

// ForbiddenOrigin defines model for ForbiddenOrigin.
type ForbiddenOrigin = Error

// GenerationFailed defines model for GenerationFailed.
type GenerationFailed = Error

// InvalidCredentials defines model for InvalidCredentials.
type InvalidCredentials = Error

// ProviderUnavailable defines model for ProviderUnavailable.
type ProviderUnavailable = Error

// SessionStarted defines model for SessionStarted.
type SessionStarted = AccessToken

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ValidationFailed defines model for ValidationFailed.
type ValidationFailed = Error

// VerificationPending defines model for VerificationPending.
type VerificationPending = PendingVerification

// WeakPassword defines model for WeakPassword.
type WeakPassword = Error

// CompleteLoginParams defines parameters for CompleteLogin.
type CompleteLoginParams struct {
	Code  *string `form:"code,omitempty" json:"code,omitempty"`
	State *string `form:"state,omitempty" json:"state,omitempty"`
}

// StartLoginParams defines parameters for StartLogin.
type StartLoginParams struct {
	Provider StartLoginParamsProvider `form:"provider" json:"provider"`

	// ReturnTo Same-app absolute path to land on after sign-in. Invalid values fall back to /dashboard.
	ReturnTo *string `form:"returnTo,omitempty" json:"returnTo,omitempty"`
}

// StartLoginParamsProvider defines parameters for StartLogin.
type StartLoginParamsProvider string

// EmailPublicSOWDocumentParams defines parameters for EmailPublicSOWDocument.
type EmailPublicSOWDocumentParams struct {
	// IdempotencyKey Opaque key for suppressing an accidental duplicate send.
	IdempotencyKey string `json:"Idempotency-Key"`
}

// EmailTemplateDocumentParams defines parameters for EmailTemplateDocument.
type EmailTemplateDocumentParams struct {
	// IdempotencyKey Opaque request key used to prevent an accidental duplicate send. Do not include an email address or contract value in this key.
	IdempotencyKey string `json:"Idempotency-Key"`
}

// ReceiveWorkOSWebhookParams defines parameters for ReceiveWorkOSWebhook.
type ReceiveWorkOSWebhookParams struct {
	// WorkOSSignature t=<unix-ms>, v1=<hex HMAC-SHA256 of "t.body">
	WorkOSSignature string `json:"WorkOS-Signature"`
}

// ForgotPasswordJSONRequestBody defines body for ForgotPassword for application/json ContentType.
type ForgotPasswordJSONRequestBody = EmailRequest

// ResendVerificationJSONRequestBody defines body for ResendVerification for application/json ContentType.
type ResendVerificationJSONRequestBody = EmailRequest

// ResetPasswordJSONRequestBody defines body for ResetPassword for application/json ContentType.
type ResetPasswordJSONRequestBody = ResetPasswordRequest

// SignInJSONRequestBody defines body for SignIn for application/json ContentType.
type SignInJSONRequestBody = Credentials

// SignUpJSONRequestBody defines body for SignUp for application/json ContentType.
type SignUpJSONRequestBody = SignUpRequest

// VerifyEmailJSONRequestBody defines body for VerifyEmail for application/json ContentType.
type VerifyEmailJSONRequestBody = VerifyEmailRequest

// DownloadPublicSOWDocumentJSONRequestBody defines body for DownloadPublicSOWDocument for application/json ContentType.
type DownloadPublicSOWDocumentJSONRequestBody = PublicSOWDownloadRequest

// EmailPublicSOWDocumentJSONRequestBody defines body for EmailPublicSOWDocument for application/json ContentType.
type EmailPublicSOWDocumentJSONRequestBody = PublicSOWEmailRequest

// DownloadTemplateDocumentJSONRequestBody defines body for DownloadTemplateDocument for application/json ContentType.
type DownloadTemplateDocumentJSONRequestBody = DocumentDownloadRequest

// EmailTemplateDocumentJSONRequestBody defines body for EmailTemplateDocument for application/json ContentType.
type EmailTemplateDocumentJSONRequestBody = EmailDocumentRequest

// ReceiveWorkOSWebhookJSONRequestBody defines body for ReceiveWorkOSWebhook for application/json ContentType.
type ReceiveWorkOSWebhookJSONRequestBody = WorkOSEvent
