// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: health.sql

package sqlcgen

import (
	"context"
)

const healthProbe = `-- name: HealthProbe :one
SELECT 1 AS alive
`

func (q *Queries) HealthProbe(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, healthProbe)
	var alive int32
	err := row.Scan(&alive)
	return alive, err
}
