// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	DeleteUser(ctx context.Context, id string) error
	GetUser(ctx context.Context, id string) (User, error)
	HealthProbe(ctx context.Context) (int32, error)
	UpsertUserIfNewer(ctx context.Context, arg UpsertUserIfNewerParams) (User, error)
}

var _ Querier = (*Queries)(nil)
